### ISSUE TITLE
If statement

### ISSUE THREAD

**Issue by joer89** [joer89/Media#11]
I have just tested this and it works so its not a issue but under the if statement on line 89, above it, should that code be in the if statement? how does it work?

From;
                #Displays the new naming convention.
                #$Pattern of the new file is 'The Simpsons 01x01'
                $NewName = $Title + " " + $Season + "x" + $Episode + $extension

                #Format filenme as per Plex naming standards (https://support.plex.tv/hc/en-us/articles/200220687-Naming-Series-Season-Based-TV-Shows)
                if ($PlexFormat) {
                    $NewName = $Title + " - S" + $Season + "E" + $Episode + $extension
                }

to;

              #Format filenme as per Plex naming standards (https://support.plex.tv/hc/en-us/articles/200220687-Naming-Series-Season-Based-TV-Shows)
                if ($PlexFormat) {
                    $NewName = $Title + " - S" + $Season + "E" + $Episode + $extension
                }
else{
                #Displays the new naming convention.
                #$Pattern of the new file is 'The Simpsons 01x01'
                $NewName = $Title + " " + $Season + "x" + $Episode + $extension

}#if

**Comment by ozthe2** [comment]
Because we only have two format styles, the original and the Plex one, we can get away with this code.
It does the original naming first, and sets the $newname var, but IF the PlexFormat switch is true, then the IF statement executes and overwrites the $Newname with the new format contained within the IF statement.   This is why the code comes after the original code that sets the name.  You could do an if \ else statement and that would work too.  Later we may add other formats in which case we will probably use a switch statement for clarity.

**Comment by joer89** [comment]
Oh i see, i was thinking on thoughts lines.
